prefix = "http://watch.peoplepower21.org"
start = prefix + "/New/search.php"
private = prefix + "/New/cm_info.php?member_seq=%s&info_page=cm_info_private.php"
special = prefix + "/New/cm_info.php?member_seq=%s&info_page=cm_info_special.php"
attend = prefix + "/New/cm_info_act_mAttend.php?member_seq=%s"
attend_page = prefix + "/New/cm_info_act_mAttend.php?member_seq=%s&page=%s"
